# services:
#   - type: web
#     name: yemen-china-blog
#     env: python
#     buildCommand: "pip install -r requirements.txt"
#     startCommand: "python manage.py migrate && gunicorn blog_project.wsgi"
#     envVars:
#       - key: DEBUG
#         value: "False"
#       - key: SECRET_KEY
#         generateValue: true
#       - key: DATABASE_URL
#         value: ""


# render.yaml
services:
  - type: web
    name: my-blog
    runtime: python
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"